[control_plane]
192.168.122.33 ansible_user=kiszka node_name=my-prod-cluster-cp-01
192.168.122.34 ansible_user=kiszka node_name=my-prod-cluster-cp-02
192.168.122.35 ansible_user=kiszka node_name=my-prod-cluster-cp-03

[workers]
192.168.122.36 ansible_user=kiszka node_name=my-prod-cluster-worker-01
192.168.122.37 ansible_user=kiszka node_name=my-prod-cluster-worker-02

[cluster:children]
control_plane
workers
