[control_plane]
192.168.122.112 ansible_user=kiszka node_name=my-prod-cluster-cp-01
192.168.122.12 ansible_user=kiszka node_name=my-prod-cluster-cp-02
192.168.122.89 ansible_user=kiszka node_name=my-prod-cluster-cp-03

[workers]
192.168.122.232 ansible_user=kiszka node_name=my-prod-cluster-worker-01
192.168.122.229 ansible_user=kiszka node_name=my-prod-cluster-worker-02

[cluster:children]
control_plane
workers
