#cloud-config
package_update: true
package_upgrade: true

packages:
  - curl
  - apt-transport-http
  - ca-certificates
  - gnupg

runcmd:
  - echo "alias k=kubectl" >> ~/.bashrc
  
  # containerd installation
  - sudo install -m 0755 -d /etc/apt/keyrings
  - sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
  - sudo chmod a+r /etc/apt/keyrings/docker.asc
  - |
    cat <<EOF > /etc/apt/sources.list.d/docker.sources
    Types: deb
    URIs: https://download.docker.com/linux/ubuntu
    Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
    Components: stable
    Architectures: $(dpkg --print-architecture)
    Signed-By: /etc/apt/keyrings/docker.asc
    EOF
  - apt update
  - apt install -y containerd.io

  # containerd config
  - mkdir -p /etc/containerd
  - containerd config default > /etc/containerd/config.toml
  - sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
  - systemctl enable containerd
  - systemctl restart containerd
  - |
    cat <<EOF > /etc/crictl.yaml
    runtime-endpoint: unix:///var/run/containerd/containerd.sock
    image-endpoint: unix:///var/run/containerd/containerd.sock
    timeout: 10
    debug: false
    EOF

  # swap config
  - sed -i '/ swap / s/^/#/' /etc/fstab
  - swapoff -a

  #kernel params config
  - modprobe overlay
  - modprobe br_netfilter
  - |
    cat <<EOF | tee /etc/modules-load.d/k8s.conf
    overlay
    br_netfilter
    EOF
  - |
    cat <<EOF | tee /etc/sysctl.d/kubernetes.conf
    net.ipv4.ip_forward = 1
    EOF
  - sysctl --system

  # configuration of package repository
  - echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.36/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
  - sudo mkdir -p -m 755 /etc/apt/keyrings
  - curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.36/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  - sudo apt-get update

  # installation of kubelet kubeadm kubectl
  - sudo apt-get install -y kubelet kubeadm kubectl
  - sudo apt-mark hold kubelet kubeadm kubectl
  - sudo systemctl enable --now kubelet

  # cluster init
  - kubeadm init --pod-network-cidr=192.168.0.0/16 --apiserver-advertise-address=$(hostname -I | awk '{print $1}')
  - mkdir -p /root/.kube
  - sudo cp -i /etc/kubernetes/admin.conf /root/.kube/config
  - sudo chown root:root /root/.kube/config
  # for default user - ubuntu
  - mkdir -p /home/ubuntu/.kube
  - cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
  - chown ubuntu:ubuntu /home/ubuntu/.kube/config
  - export KUBECONFIG=/etc/kubernetes/admin.conf
 
  # cilium installation
  - |
    CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/main/stable.txt)
    CLI_ARCH=$(dpkg --print-architecture)
    curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-${CLI_ARCH}.tar.gz
    tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
    rm cilium-linux-${CLI_ARCH}.tar.gz
    KUBECONFIG=/root/.kube/config cilium install
  
  # rancher local-path provisioner installation
  - kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.35/deploy/local-path-storage.yaml
  - kubectl wait --for=condition=Available deployment/local-path-provisioner -n local-path-storage --timeout=300s
  - kubectl patch storageclass local-path -p '{"metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

  # helm installation
  - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
